### ISSUE TITLE
CAP: Aggregated CDS View returns incorrect $count Value

### ISSUE THREAD

**Issue by ckuczera** [sapmentors/cap-community#109]
Dear CAP Community,

we are working on a hugh project with CAP / Node.js and currently facing an issue with aggregated CDS Views.

Whenever a aggregation is processed ob the Entity, the $count variable returned in the responce always contains the whole amount (filtered) of datasets of the database and not the count of "pageable" entries which leads to an incorrect paging visualization and a browser out of memory error in an Analytical Page App:

The CDS View is setup as aggregated view with summed up mesures:
`// Costs Analytics View
@readonly
@cds.redirection.target : true
@Aggregation.ApplySupported.PropertyRestrictions : true 
define view CostsAnalytics as select from db.XXXCosts { 
key ID,
@Analytics.Dimension : true 
perfDate,
@Analytics.Dimension : true
distributionDate, 
... 
@title: '{i18n>NetCost}'<br>@Analytics.Measure : true 
@Aggregation.default : #SUM round( netCost, 2 ) as netCost : Decimal(15, 2), 
@title: '{i18n>TaxCost}' 
@Analytics.Measure : true 
@Aggregation.default : #SUM round( taxCost, 2 ) as taxCost : Decimal(15, 2),
@title: '{i18n>GrossCost}' 
@Analytics.Measure : true 
@Aggregation.default : #SUM round( grossCost, 2 ) as grossCost : Decimal(15, 2) 
};`

Example odata V4 Request:
`/srv_api/aggregated-costs/CostsAnalytics?$top=100&$count=true&$apply=filter((((costYear eq '2021'))))/groupby((costYearMon),aggregate(taxCost with sum as __AGGREGATION__taxCost,netCost with sum as __AGGREGATION__netCost,grossCost with sum as __AGGREGATION__grossCost))`
Returns an odata count of "@odata.count": 67461606,
In fact, the result countains 12 entries (one per month). 

I already created a question in SAP Community, which is not answered until now:
https://answers.sap.com/questions/13523259/analytical-list-page-and-aggregated-cap-view-crash.html

BR
Christoph

**Comment by ckuczera** [comment]
Update: We have updated to @sap/cds-odata-v2-adapter-proxy 1.8.1. Now the page is loading, but no $count is transfered to odata v2

**Comment by gregorwolf** [comment]
Dear @ckuczera,

please ask this question in the [SAP Community CAP Q&A](https://answers.sap.com/tags/9f13aee1-834c-4105-8e43-ee442775e5ce) as the traffic here is low.
