### ISSUE TITLE
SQL window functions in CAP CDS

### ISSUE THREAD

**Issue by mangoldd** [sapmentors/cap-community#110]
Hello,
just wondering because I did not find any information and compiler does not accept the syntax:
is there no support for (SQL) window functions in CAP cds?
Thanks,
Daniel

**Comment by gregorwolf** [comment]
Please post such questions [in the SAP Community Q&A](https://answers.sap.com/tags/9f13aee1-834c-4105-8e43-ee442775e5ce)
