### ISSUE TITLE
CAP Nodejs POST request with headers

### ISSUE THREAD

**Issue by T1mey** [sapmentors/cap-community#114]
Hello CAP community,

we used this code snipet to connect to an external service and send a POST request with additional headers.
Now with "@sap/cds": "^5.9.6" we have some problems.

```
const sscApi = await cds.connect.to('SOME_DEST');
let jobResponse = await sscApi.send({ query: 'POST /createItem?name=' + name, data: xml, headers: { 'Content-Type': 'application/xml', 'Jenkins-Crumb': jenkinsCrumb } });
```

For some reason this request is now running in an error.

`innererror: Error: Error during request to remote service: timeout of 60000ms exceeded`

As well we realized that for other POST calls no string is allowed for the payload anymore. Same timout error. We changed to the JSON object and it's working again. 

What needs to be changed for the above call to work again?

**Comment by gregorwolf** [comment]
Hi @T1mey,

please post the question in the SAP Community at https://answers.sap.com/tags/9f13aee1-834c-4105-8e43-ee442775e5ce. There you should get more attention.
