### ISSUE TITLE
@cds.on.insert: #user returns value of #now.

### ISSUE THREAD

**Issue by dvvelzen** [sapmentors/cap-community#27]
Hi,

When I use @cds.on.insert: #user as described on https://cap.cloud.sap/docs/guides/generic-providers#administrative-data the value that is inserted is #now instead of #user. 

db/
```
entity Test {
    key ID: Integer;
    @cds.on.insert: #user
    usr: String;
}
```

srv/
```
@Capabilities: { Insertable:true, Updatable:true, Deletable:false }
entity Test as projection on my.Test;
```

Postman POST
```
{
	"ID": 1
}
```

Response:
```
{
    "@odata.context": "$metadata#Test/$entity",
    "@odata.metadataEtag": "W/\"Z8vYLBwhpE88xl0GqG7dG6jh6IDcOeIONQBT8O5NY1s=\"",
    "ID": 1,
    "usr": "2020-01-15T17:01:35.173Z"
}
```

Data from Postman GET:
```
{
    "@odata.context": "$metadata#Test",
    "@odata.metadataEtag": "W/\"Z8vYLBwhpE88xl0GqG7dG6jh6IDcOeIONQBT8O5NY1s=\"",
    "value": [
        {
            "ID": 1,
            "usr": "2020-01-15T17:01:35.173Z"
        }
    ]
}
```

The response and the saved value are incorrect they should be anonymous in this case.

Changing updatable in the srv/
```
@Capabilities: { Insertable:true, Updatable:false, Deletable:false }
entity Test as projection on my.Test;
```

Postman Response:
```
{
    "@odata.context": "$metadata#Test/$entity",
    "@odata.metadataEtag": "W/\"JgUx0o1vV3RvDxgdNoz2tqILWXhgpO67KWVu8rVJZd4=\"",
    "ID": 1,
    "usr": null
}
```

Data from GET:
```
{
    "@odata.context": "$metadata#Test",
    "@odata.metadataEtag": "W/\"JgUx0o1vV3RvDxgdNoz2tqILWXhgpO67KWVu8rVJZd4=\"",
    "value": [
        {
            "ID": 1,
            "usr": "anonymous"
        }
    ]
}
```

The response is incorrect the "usr" value should be anonymous.

The first issue is plain wrong the value should be that of #user not #now.
The second issues is alike: [CAP insertable service error with DB defaults #25](https://github.com/sapmentors/cap-community/issues/25
)

/D

**Comment by vobu** [comment]
seems to be some old-ish doc you hit up.
I only know of the syntax
`@cds.on.update : $now`
and
`@cds.on.update : $user`

**Comment by dvvelzen** [comment]
You are correct with $ instead of # the value is not turning into a timestamp.

So it's a doc issue @ https://cap.cloud.sap/docs/guides/generic-providers 

Thanks.

**Comment by vobu** [comment]
can someone from CAP core take and PR-fix this for cap.cloud.sap please? :)

**Comment by iwonahahn** [comment]
I will take care of it tomorrow and get back to you here.

**Comment by iwonahahn** [comment]
The documentation was updated and will be published soon on capire. I´ll provide the link asap here.

**Comment by iwonahahn** [comment]
Here we go ...  updated content for [managed data](https://cap.cloud.sap/docs/guides/generic-providers#managed-data).
