### ISSUE TITLE
Entities available without authentication using non-existing URLs

### ISSUE THREAD

**Issue by IcyT** [sapmentors/cap-community#35]
Hello,

I have a service deployed on CF using @(requires: 'authenticated-user'). Calling the service directly without app router (/myservice/myentityset) results in an unauthorized error, which is what I expect. Now the security issue: If I add another path in the URL the service is callable without authentication (e.g. /NONEXISTINGPATH/myservice/myentityset). This is a severe security issue!

Thanks and best regards,
Thorsten

**Comment by gregorwolf** [comment]
I was able to replicate it when running my demo project https://github.com/gregorwolf/bookshop-demo with `npm run start` i can access http://localhost:4004/NONEXISTINGPATH/admin/Books without authentication. http://localhost:4004/admin/Books prompts me for authentication. When I include the V2 Proxy by starting it with `npm run startv2` and I try  http://localhost:4004/NONEXISTINGPATH/admin/Books  the answer is: Cannot GET /NONEXISTINGPATH/admin/Books. So quick fix: Use the V2 Proxy.

**Comment by danjoa** [comment]
Will follow up asap. 
Thanks for triggering me, Thorsten

**Comment by chgeo** [comment]
A fix is on the way and expected for today.  Stay tuned...

**Comment by chgeo** [comment]
`@sap/cds` 3.21.3 has been released with a fix for the issue.

Thanks for reporting!

**Comment by IcyT** [comment]
Thanks a lot!
