### ISSUE TITLE
Restrict with user attribute does not work with mock user

### ISSUE THREAD

**Issue by korayyersel** [sapmentors/cap-community#37]
Hi, 

We have tried out the mock user features for local development. 

I have a mock user looking like this:
`"users": {
          "koray": {            
            "roles": [
              "qperiordemorole"
            ],
            "userAttributes": { "country": "CH" }
          }        
        }`
"Requires" on service level works fine using this mock user
`service CatalogService @(requires : 'qperiordemorole') {`
Only with user "koray" I can call the entities from the service.
But if I want to make a restriction like this:
`    entity DVDs @readonly @(restrict : [{
        grant : 'READ',
        to    : 'qperiordemorole',
        where : 'country = $user.country'
    }])            as projection on qperiordemo.DVDs;`
I still get all items from the entity. Not only "CH" entries. If I deploy the solution on CF the restriction works fine. So I thought this should be a bug for mock users + restriction usage.
Regards,
Koray

**Comment by olirogers** [comment]
Hi Koray,

I have a working example of this in the `issues/user-attrs` folder of this repo.

The property should be "attributes" not "userAttributes" (I think this might be against the documentation but it works!!) and the value is an array of valid values, so in your case:

`"users": { "koray": { "roles": [ "qperiordemorole" ], "attributes": { "country": [ "CH" ] } } }`

See
[https://github.com/sapmentors/cap-community/blob/master/issues/user-attrs/package.json#L49](https://github.com/sapmentors/cap-community/blob/master/issues/user-attrs/package.json#L49
)

Hope this helps!

**Comment by korayyersel** [comment]
Works like a charm! Thanks for the quick response
