### ISSUE TITLE
Documentation: Spelling Mistake Entity Auhtors

### ISSUE THREAD

**Issue by d023604** [sapmentors/cap-community#40]
Small spelling mistake in the documentation of [https://cap.cloud.sap/docs/guides/domain-models#about-domain-models](url) in the section Use Canonic Primary Keys.

Entity Auhtors instead of Entity Authors

Admittedly not world changing, but caught my eye..

**Comment by iwonahahn** [comment]
Thanks for reporting this. We will fix this today :).

**Comment by iwonahahn** [comment]
Issues was fixed weeks ago, see https://cap.cloud.sap/docs/guides/domain-models#use-canonic-primary-keys. Issue can be closed @gregorwolf.

**Comment by gregorwolf** [comment]
Please confirm @d023604

**Comment by iwonahahn** [comment]
Can we close it?
