### ISSUE TITLE
Documentation: Small spelling mistake in Domain Models

### ISSUE THREAD

**Issue by d023604** [sapmentors/cap-community#41]
Small spelling mistake in the documentation of [https://cap.cloud.sap/docs/guides/domain-models#about-domain-models](url) in the section Domain Driven Design

> Domain modelling as a service — Domain models **ar** only a means to an end: ...

Admittedly not world changing, but caught my eye..

**Comment by iwonahahn** [comment]
Thanks for reporting this. We will fix this today :).

**Comment by iwonahahn** [comment]
Issues was fixed weeks ago, see https://cap.cloud.sap/docs/guides/domain-models#keep-them-simple. Issue can be closed @gregorwolf.
