### ISSUE TITLE
Documentation: Small Spelling Mistake in Domain Models

### ISSUE THREAD

**Issue by d023604** [sapmentors/cap-community#42]
Small spelling mistake in the documentation [in the section Use Canonic Primary Keys](https://cap.cloud.sap/docs/guides/domain-models#use-canonic-primary-keys) 

> For example they can turn this recommendation of using canonic primary keys into a project-wide policy by **usins** base types and aspects as follows:

Admittedly not world changing, but caught my eye..

**Comment by iwonahahn** [comment]
Thanks for reporting this. We will fix this today :).

**Comment by iwonahahn** [comment]
Issues was fixed weeks ago, see https://cap.cloud.sap/docs/guides/domain-models#use-canonic-primary-keys. Issue can be closed @gregorwolf.
