### ISSUE TITLE
Documentation: Spelling Mistake in Generic Providers

### ISSUE THREAD

**Issue by d023604** [sapmentors/cap-community#43]
Small spelling mistake in the documentation of Generic Providers in the section With Order By in Entity Definition

> Now, assumed we might want to **definde** a default order

Admittedly not world changing, but caught my eye..

**Comment by iwonahahn** [comment]
Thanks for reporting this. We will fix this today :).

**Comment by iwonahahn** [comment]
Issues was fixed weeks ago, see https://cap.cloud.sap/docs/guides/providing-services#implicit-sorting. Issue can be closed @gregorwolf.
