### ISSUE TITLE
Documentation: Spelling Mistake in Defining Services

### ISSUE THREAD

**Issue by d023604** [sapmentors/cap-community#44]
Small spelling mistake in the documentation of Defining Services in the example under All-in-one Definitions. (providing-services.html)

> entity LibraryService {
>   **enity** Books {

Admittedly not world changing, but caught my eye..

**Comment by iwonahahn** [comment]
Thanks for reporting this. We will fix this today :).

**Comment by iwonahahn** [comment]
Issues was fixed weeks ago, see https://cap.cloud.sap/docs/guides/providing-services#all-in-one-definitions. Issue can be closed @gregorwolf.
