### ISSUE TITLE
[Docu] Restriction not required anymore

### ISSUE THREAD

**Issue by wattnu** [sapmentors/cap-community#50]
According to https://cap.cloud.sap/docs/cds/cql#current-limitations, statements like ``entity Bar as SELECT * from Foo;`` are not supported. According to my own experiments this works well. Some outdated docu artifact?
Regards,
Klaus

**Comment by wattnu** [comment]
Here is another one: 

https://cap.cloud.sap/docs/cds/cdl#records-as-syntax-shortcuts states that:
```
@Common: { foo.bar, foo.car: 'wheels' }
//> not yet implemented!
```
Seems to work however with cds 3.31.2

**Comment by iwonahahn** [comment]
Hi,

Thank you for reporting this. We will check this with the dev colleagues and get back here.

Best regards,
Iwona

**Comment by iwonahahn** [comment]
Hi Klaus,

We have updated the mentioned parts in the docs and removed the limitation here [https://cap.cloud.sap/docs/cds/cql#query-local-mixins](https://cap.cloud.sap/docs/cds/cql#query-local-mixins).

For the second one, we have removed the comment, cause it works as you have figured out :).
If you are fine with these changes we can close the issue.

Best regards,
Iwona
