### ISSUE TITLE
Documentation: Dead link

### ISSUE THREAD

**Issue by wattnu** [sapmentors/cap-community#52]
Hi
Please check https://cap.cloud.sap/docs/guides/localized-data.
The mention link https://github.com/SAP-samples/cloud-cap-samples/tree/master/packages/bookshop is not working.
Probably, it should be now https://github.com/SAP-samples/cloud-cap-samples/tree/master/bookshop

Regards
Klaus

**Comment by iwonahahn** [comment]
Hi Klaus,

We have updated the samples and the link has changed today. We will update it latest tomorrow.

Best regards,
Iwona
