### ISSUE TITLE
Documentation: Search shows result for search term virtual on page "Providing Services" but no results there

### ISSUE THREAD

**Issue by gregorwolf** [sapmentors/cap-community#57]
I was using the CAP Documentation search for the term "virtual" and got this result list:

![Screenshot 2020-04-06 at 18 09 04](https://user-images.githubusercontent.com/2639535/78579833-d3c73580-7831-11ea-9057-e05e071b0afd.png)

When navigating to the page: https://cap.cloud.sap/docs/guides/providing-services I've tried to find the term on the page:

![Screenshot 2020-04-06 at 18 09 18](https://user-images.githubusercontent.com/2639535/78579841-d6c22600-7831-11ea-9d8c-5739034f60ed.png)

but as you can see got no results.

**Comment by wattnu** [comment]
Hello CAP Team,
This is a "feature" I'm also recognizing from time to time. There seem to be hidden resources, which affect the search results. Would  be good to exclude those from search ...
Regards

**Comment by iwonahahn** [comment]
Hi together,

Thank you for reporting this. We will check this with the dev colleagues and get back here.

Best regards,
Iwona

**Comment by iwonahahn** [comment]
Hi @gregorwolf and @wattnu ,
First, thank you for your feedback and your patience. We have analyzed the problem and fixed it. Parts of the documentation are currently being updated internally. These parts should no longer appear in the search results. If we publish new content, you will find out in our monthly [release notes](https://cap.cloud.sap/docs/releases/). Please try it out again with the search term you have used and close the issue.
Best regards and have a nice weekend,
Iwona

**Comment by gregorwolf** [comment]
LGTM
