### ISSUE TITLE
Build options not working

### ISSUE THREAD

**Issue by wattnu** [sapmentors/cap-community#65]
I'm using cds-dk  1.8.0 or 1.7.1 on Windows 10. I've found that most of the  build options described by ``cds help build`` are not working anymore. Example:
```
>> cds build --log-level info
[ERROR] invalid option: --log-level
    at Object.exports.parseArgs (C:\Users\\AppData\Roaming\npm\node_modules\@sap\cds-dk\node_modules\@sap\cds\bin\utils\cli.js:46:11)
    at Module.exports (C:\Users\\AppData\Roaming\npm\node_modules\@sap\cds-dk\node_modules\@sap\cds\bin\cds.js:43:53)
    at Object.<anonymous> (C:\Users\\AppData\Roaming\npm\node_modules\@sap\cds-dk\bin\cds.js:32:10)
    at Module._compile (internal/modules/cjs/loader.js:1133:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1153:10)
    at Module.load (internal/modules/cjs/loader.js:977:32)
    at Function.Module._load (internal/modules/cjs/loader.js:877:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12)
    at internal/main/run_main_module.js:18:47
>>
```

**Comment by lobero** [comment]
Hi Klaas,
thanks for filing this issue. It has been introduced when replacing the legacy build with new modular build system - now the only build command is ``cds build` - `cds build/all` has been deprecated.

The issue will be fixed with next cds release version.

Regards,
Lothar

**Comment by wattnu** [comment]
Thanks Lothar!
Will test it and then close this ...

**Comment by wattnu** [comment]
Hi Lothar,
I don't see the fixes in the new May release. What are the plans for the fix?
Thanks
```
>> cds -v
@sap/cds: 3.34.2
@sap/cds-compiler: 1.26.2
@sap/cds-dk: 1.8.5
@sap/cds-foss: 1.2.0
@sap/cds-reflect: 2.11.0
@sap/cds-runtime: 1.2.2
@sap/xsenv: 2.2.0
Node.js: v12.16.3
```
@lobero

**Comment by lobero** [comment]
Hi Klaus,
I could successfully execute
`cds build --for hana --src db --dest db/gen --options-model db,srv --log-level info` 

Are you looking for different fixes?
Not all fixes have been downported to 3.34, but I thought this is one of them you have been waiting for...

Regards,
Lothar

**Comment by wattnu** [comment]
Hi Lothar,
Indeed, ``cds build --for hana --src db`` is working for me as well! I was trying to execute ``cds build --for hana`` without the ``src``-option. This is not working. I was expecting that the default db-folder would kick-in, as it happens when just doing ``cds build``.
Regards

**Comment by lobero** [comment]
Hi Klaus,
thanks for the feedback - I see your point...

Actually the 4.0 version does not require the `--src` option, but cwd is used instead of the build task type specific default src-folder (db, srv, app). I was thinking in the direction that `cds build --for hana` is simply somehow an extension to `cds build`. And `cds build` is using cwd by default.

If thinking in the direction of build tasks your idea might be the better choice and this might be indeed what users would expect ;-)
From an implementation perspective it would mean that the corresponding default build task would have to be retrieved in order to overwrite any of its properties that have been passed as CLI options.

Regards

**Comment by wattnu** [comment]
Hi Lothar,
From my end user perspective, looking at the example `` cds build --for hana --src db --dest db/gen --options-model db,srv`` suggests, that this command is executing an ad-hoc build task. So, when leaving out some command line parameters, the configured Hana build task can fill these in. Makes high sense for me. Of course, if there is no explicit build task config, then the default is relevant.

Shall I leave this issue open?

Regards

**Comment by lobero** [comment]
Hi Klaus,
as discussed - changes will be part of the upcoming version 4.x.

I think we can close this issue.

Regards,
Lothar
