### ISSUE TITLE
Odata V2 adapter  for CAP service

### ISSUE THREAD

**Issue by shyamkumarc** [sapmentors/cap-community#68]
When i try to use Odata V2 adapter( github.com/gregorwolf/SAP-NPM-API-collection/tree/master/apis/cds-odata-v2-adapter-proxy ) , the V2 link gives an internal server error response. I chose the "CDS combined backend (Node.js) - custom" for my use case - when i run index.js , it works fine for V4 , but for the V2 path it gives internal server error. A look at the log for the service shows an error as follows: "Error: CDS compilation failed\ncat-service.cds:1:40-58: Error: Cannot find local module '../db/data-model' .

I'm sharing a Github link to my sample project here : https://github.com/shyamkumarc/CAP_POC

Please guide.

**Comment by gregorwolf** [comment]
Please adjust your project to use the generated csn.json as I did in [v2server.js#L9](https://github.com/gregorwolf/bookshop-demo/blob/master/srv/v2server.js#L9). At runtime in CF cds doesn't have access to the db folder that contains the DB schema. So you have to point the proxy to a static resource that is available in srv.

**Comment by shyamkumarc** [comment]
Thanks a Lot @gregorwolf ! it worked 👍
