### ISSUE TITLE
Annotation @cds.persistence:{mock:false} not documented

### ISSUE THREAD

**Issue by gregorwolf** [sapmentors/cap-community#69]
Currently the documentation for [Common Annotations - Persistence](https://cap.cloud.sap/docs/cds/annotations#persistence) does not contain the Annotation 
@danjoa has mentioned in https://github.com/sapmentors/cap-community/issues/59#issuecomment-624573307

` @cds.persistence:{mock:false} `

Looking forward to see all possibilities in the documentation.

**Comment by danjoa** [comment]
Just added it... → you can already see it in internal capire

**Comment by iwonahahn** [comment]
Thanks @danjoa

**Comment by iwonahahn** [comment]
@gregorwolf once it is published on capire I´ll post it here and you can close the issue.

**Comment by iwonahahn** [comment]
@gregorwolf content was published today. You can close the issue.

**Comment by gregorwolf** [comment]
Thank you.
