### ISSUE TITLE
Documentation for predefined roles not available

### ISSUE THREAD

**Issue by htammen** [sapmentors/cap-community#71]
Hi SAP CAP documentation team,
in the current open.sap.com course "Building Applications with SAP Cloud Application Programming Model" week 3, unit 5 the predefined roles "authenticated-user, identified-user,system-user,any" were mentioned. It was said that there is more info about these roles in the capire online documentation (https://cap.cloud.sap/docs/). 
I tried to find this documentation but it seems not to be available. In a cource specific thread the following link was mentioned but this is also not available https://cap.cloud.sap/docs/guides/authorization#pseudo-roles.
Can you please update the documentation?

Thanks in advance
Helmut

**Comment by iwonahahn** [comment]
Hi Helmut,

Thanks for reporting it. I will fix the link and let you know once the content is available.

Best regards,
Iwona

**Comment by iwonahahn** [comment]
Hi Helmut,

The content is available here https://cap.cloud.sap/docs/guides/authorization#pseudo-roles. We can close the issue.

Best regards,
Iwona

**Comment by htammen** [comment]
Thank you very much

Best regards 
Helmut
