### ISSUE TITLE
Documentation: Missing FQNs

### ISSUE THREAD

**Issue by wattnu** [sapmentors/cap-community#74]
I've found two place in https://cap.cloud.sap/ where I think the code samples are wrong:

First is at https://cap.cloud.sap/docs/node.js/api#cds-transaction. The sample shows
```
return tx.run (SELECT.from ('Books'))
```
IMO, this must be changed to use the fully qualified name, like
```
return tx.run (SELECT.from ('another-service.Books'))
```
The same hold for the sample at https://cap.cloud.sap/docs/guides/consuming-services#uniform-consumption

In the same spirit, the ``Common Usage`` samples at https://cap.cloud.sap/docs/node.js/api#cds-run-query  and https://cap.cloud.sap/docs/node.js/api#cds-connect seem to be misleading.

Regards

**Comment by iwonahahn** [comment]
Thank you. We will have a look at it and get to you back here asap. 
Best regards,
Iwona

**Comment by iwonahahn** [comment]
We have updated and republished the docs. Please check:

https://cap.cloud.sap/docs/node.js/api#cds-transaction

https://cap.cloud.sap/docs/guides/consuming-services#uniform-consumption

https://cap.cloud.sap/docs/node.js/api#cds-run-query

https://cap.cloud.sap/docs/node.js/api#cds-connect

If you are satisfied we can close this issue.
Best regards,
Iwona

**Comment by wattnu** [comment]
Ad https://cap.cloud.sap/docs/node.js/api#cds-run-query:
It still looks like this:
```
const srv = await cds.connect.to ('SomeService') // > could be a local service, a remote one or a databasde
const books = await srv.run (SELECT.from('my.bookshop.Books'))
```
To align with the other similar examples, better use the pattern
```
const srv = await cds.connect.to ('SomeService') // > could be a local service, a remote one or a databasde
const { Books } = srv.entities
const books = await srv.run (SELECT.from(Books))
```

**Comment by iwonahahn** [comment]
Hi @wattnu, 

The issue was fixed here https://cap.cloud.sap/docs/node.js/api#cds-run-query and issue can be closed.

Best regards,
Iwona
