### ISSUE TITLE
Documentation: Missing single quotes

### ISSUE THREAD

**Issue by wattnu** [sapmentors/cap-community#76]
Hi
Looking at https://cap.cloud.sap/docs/node.js/api#select-forUpdate, I guess, that in both sample code sections, ``ID`` must be in single quotes: ``ID`` --> ``'ID'``

Regards

**Comment by iwonahahn** [comment]
Thank you. We will have a look at it and get to you back here asap.
Best regards,
Iwona

**Comment by danjoa** [comment]
No, `ID` is meant to be a variable obtained from somewhere in these examples → hence:
```js
SELECT.from(Authors,ID)
```
is a shortcut for the like of:
```js
SELECT.one..from(Authors).where({ID})
```
or:
```js
SELECT.one..from(Authors).where('ID=',ID)
```
