### ISSUE TITLE
Documentation: ".values" instead of ".columns"

### ISSUE THREAD

**Issue by wattnu** [sapmentors/cap-community#77]
Hi
In https://cap.cloud.sap/docs/node.js/api#INSERT --> section ".columns(...)": The text states "subsequently specified .rows or .columns.". Should be "subsequently specified .rows or **.values**. "

Regards

**Comment by iwonahahn** [comment]
Thank you. We will have a look at it and get to you back here asap.
Best regards,
Iwona

**Comment by iwonahahn** [comment]
It was fixed in the documentation [https://cap.cloud.sap/docs/node.js/api#INSERT](https://cap.cloud.sap/docs/node.js/api#INSERT).
