### ISSUE TITLE
Documentation: cds.load für .json

### ISSUE THREAD

**Issue by wattnu** [sapmentors/cap-community#78]
Hi
See https://cap.cloud.sap/docs/node.js/api#cds-load

There, an order of file loading depending on file extensions is listed. What about the good old ``.json``-extension? My tests show that this is still considered, right after ``.csn``. Is this just missing in the docu, or is json-loading deprecated?

Regards

**Comment by iwonahahn** [comment]
Thank you. We will have a look at it and get to you back here asap.
Best regards,
Iwona

**Comment by danjoa** [comment]
Hi @wattnu, you are right `.json` is still supported, but sort of silently deprectated (as it never was publicly documented) → you should prefer `.csn` as that has less risks of accidentally picking wrong `.json` files.
