### ISSUE TITLE
Documentation: cds.reflect.services is not a function

### ISSUE THREAD

**Issue by wattnu** [sapmentors/cap-community#79]
Hi
See https://cap.cloud.sap/docs/node.js/api#ds-entities

The "typical usages" sample is wrong, because ``m.services'' is not a function but an array. At least with cds version 3.34.1. So either the docu is wrong, or the reflection API has not been implemented as it should be.

Regards

**Comment by iwonahahn** [comment]
Thank you. We will have a look at it and get to you back here asap.
Best regards,
Iwona

**Comment by iwonahahn** [comment]
It was fixed in the documentation https://cap.cloud.sap/docs/node.js/api#ds-entities.
