### ISSUE TITLE
Mocking of imported services sometimes not working

### ISSUE THREAD

**Issue by wattnu** [sapmentors/cap-community#89]
Hi CAP-Team,
When importing a service definition with ``cds import`` and running ``cds watch``, then sometimes mocking for the imported service is not working. Actually, it seems to be an alternating issue. Restarting the watch-server in sequence, let mocking be active/no-active in an alternating way ...

I'm running Windows with:
```
>> cds -v
@sap/cds: 3.34.2
@sap/cds-compiler: 1.26.2
@sap/cds-dk: 1.8.5
@sap/cds-foss: 1.2.0
@sap/cds-reflect: 2.11.0
@sap/cds-runtime: 1.2.2
Node.js: v12.16.3
home: C:\Users\\AppData\Roaming\npm\node_modules\@sap\cds-dk\node_modules\@sap\cds
prod-cat: 1.0.0
```

**Comment by iwonahahn** [comment]
Hi Klaus,

can you please ask this question in SAP Community Q&A for [CAP](https://answers.sap.com/tags/9f13aee1-834c-4105-8e43-ee442775e5ce). As mentioned in capire the dev team tracks the mentioned [support](https://cap.cloud.sap/docs/support) channels. 

Thank you and best regards,
Iwona

**Comment by wattnu** [comment]
https://answers.sap.com/questions/13089537/mocking-of-imported-services-sometimes-not-working.html
